### ISSUE TITLE
Design Proposal

### ISSUE THREAD

**Issue by jimfrize** [Awesome-Game-Team/Awesome-Game#11]
I thought I'd put together a mockup, so I can show some of the ideas I've been thinking about.
Please check out the 15 second animation I've attached to this post.

I was thinking that the character, "Channa Boy" could go around collecting seeds to increase his energy level/score. I was also thinking about having special "Rainbow Seeds" that can give you a randomly selected power-up such as the jetpack/ flying mode.

Please let me know your thoughts :)

[mockup.mp4.zip](https://github.com/metalx1000/Awesome-Game/files/264512/mockup.mp4.zip)

**Comment by metalx1000** [comment]
Sounds good to me.

**Comment by OneSleepyDev** [comment]
I like it!

**Comment by jimfrize** [comment]
@OneSleepyDev

It's getting there. Got most of the things in the proposal started. Here's a link to its current state:

http://sonodrome.co.uk/Awesome-Game/index.html

The seeds do bring a little something to the game, I could actually imagine myself having fun playing it :)

**Comment by OneSleepyDev** [comment]
@jimfrize It plays great. I had fun. :3

(Once the merge issue get's resolved I'll update my fork and begin with some enhancements myself. In this direction of course.)

**Comment by jimfrize** [comment]
@OneSleepyDev Thanks man! I don't think we have a fixed direction, I think we just chip in ideas and see what sticks.

It's a bit weird, working together like this. I feel like @metalx1000 has invited me into his house and I've just started decorating and moving the furniture around! It's an interesting process, I'm intrigued to see what direction the game takes.

Thanks @metalx1000 for inviting us to your project, I really appreciate it :)

**Comment by jimfrize** [comment]
I've also been thinking about other powerups we could have, like; super-speed, flea jump and zero-g. Looking at the player parameters, they should be easy enough to do.

**Comment by metalx1000** [comment]
I love the direction we are going in as well.  @jimfrize your art is great!  I also love that I'm learning a bit more about Git than just using it to store my code online.  Hitting some bumps, but moving along.  I feel like I'm doing more organizing then code writing, but as time goes on and we learn more about how this works, I feel that I'll sort through that stuff faster.

Thanks @jimfrize and @OneSleepyDev
