### ISSUE TITLE
Damage and health

### ISSUE THREAD

**Issue by metalx1000** [Awesome-Game-Team/Awesome-Game#17]
So we need to start making some enemies.
How do we want to do damage and health.
I was thinking maybe like Sonic the Hedgehog.  
If you have seed and get hit your seed go flying and you have a little time to collect them back.
If you get hit with no seeds you die.  

I was also thinking about attacks.  Make you can spit the seeds, so more seeds you have the more ammo you have, but more you use the closer you are to running out and dying if hit.

Power ups can give you more powerful seed shooting abilities, but some might also use up more seed ammo.

What do you guys think?

**Comment by OneSleepyDev** [comment]
Seeds = Points, 1-hit shield, projectile ammo? That sounds good to me.

But there's also the Jazz the Jackrabbit style(also MegaMan): https://youtu.be/b16upFloYak
Health bar, variety of weapons as pick ups, points for destroying enemies and collecting ..erhm ... things.

This might be a bit ambitious to suggest this, but there could be modes implemented.
Sort of like: Basic/Advanced
Or: Simple/Complex

**Comment by jimfrize** [comment]
I vote for spitting seeds and sonic style damage and health, that sounds great. Although I'm not a big fan of killing things. Maybe, when we hit a "bad guy/whatever" they can be turned into a plant which our character collects to gain points or pass the level. Like - collect 20 plants to win!

+1 vote for a rapid fire powerup :)

**Comment by metalx1000** [comment]
Not killing the bad guys?  We might be a little split on this issue.  :/
Are the bad guys not allowed to kill us?

**Comment by jimfrize** [comment]
@metalx1000 Lol, I'm just a dippy hippy. I don't want to kill em, just turn em good!

I think the bad guys should be able to kill us, just not the other way around - it's a tough world for a pacifist chickpea, not only has he got no hands, but everyone is out to kill him!

I'm happy either way though, I'm not fussy. But if there was a vote, I'd vote for transforming the bad guys into plants and collecting them.

**Comment by jimfrize** [comment]
@metalx1000 I guess we can always do both. Maybe flower morphing power could be a seperate powerup. And the flowers could be worth 10 seeds or ammo, or something.

**Comment by metalx1000** [comment]
I mean, it doesn't have to be brutal or violent, I'm talking Mario or Tux style.  They get hit, they fall of the screen or something.

**Comment by jimfrize** [comment]
Maybe he could eat the enemy? His mouth does look pretty big - in proportion to his body

**Comment by OneSleepyDev** [comment]
If they were to turn into something and grant points(or something) it gives players a reason to find and collect them. I usually skip over enemies and run through the level in most platformers.

**Comment by metalx1000** [comment]
@jimfrize HAHA!!! You don't want to kill them, but you want to eat them alive?

@OneSleepyDev yeah, maybe when hit they can turn into a puff of smoke and leave an item behind.

**Comment by jimfrize** [comment]
@metalx1000 Yeah that's accepatble, at least then the chickpea/parrot-with-no-body can get some nutrition from his kills.

**Comment by OneSleepyDev** [comment]
Or some sparkle effects :P
Items could be randomized. Or enemies could denote type of drops based on color.

**Comment by jimfrize** [comment]
@OneSleepyDev I love the idea of randomizing the powerups, I think it would make things more exciting :)
