### ISSUE TITLE
Game Goals

### ISSUE THREAD

**Issue by metalx1000** [Awesome-Game-Team/Awesome-Game#2]
As a user I would like to collect coins/dots/food/time/kittens with my character

**Comment by jimfrize** [comment]
I agree, I think it would be nice to collect food/whatever to charge up a power bar for some kind of super-cool special move that warps time and space.

**Comment by jimfrize** [comment]
I was thinking of collecting seeds - they're nutritious and delicious ;)

#11 please see my design proposal to get an idea about how that might look.

**Comment by metalx1000** [comment]
He eats seeds.  Closing this for now.
