### ISSUE TITLE
Landing after jumps

### ISSUE THREAD

**Issue by jimfrize** [Awesome-Game-Team/Awesome-Game#24]
When landing after jumps the character bounces and kind of skids along before the walking animation starts again. If you remove the player.body.bounce.y then this doesn't happen any more. What do people think about this?

**Comment by OneSleepyDev** [comment]
I had this same issue when I tried to implement it last week before leaving town! Glad someone else thought about it too.

We could add a delay to the jump animation, around 1-1.5 seconds of animation, then stop on the running(jumping) frame. Or we can remove the bounce, w/e works.

**Comment by metalx1000** [comment]
@jimfrize I'm ok with losing the bounce, it makes it a little hard to do a second jump anyway.  Lets just comment that line out in case we decide we want it in later.  

I'm a little confused with your comment @OneSleepyDev, it sounds like you are talking about the start of the jump, not the end.  am I just misunderstanding?

**Comment by OneSleepyDev** [comment]
@metalx1000 Yep, at the start. When I had coded my solution to it , it would go to the run(jump) frame when it bounced each time; which looked like a stutter. By adding that delay the char would look like they're still running.

**Comment by metalx1000** [comment]
For now I set bounce to "0"
