### ISSUE TITLE
Enemies

### ISSUE THREAD

**Issue by metalx1000** [Awesome-Game-Team/Awesome-Game#30]
Started work on our first enemy today.
A simple Jumper.

Player can get hit by him and seed count set to '0' when hit.

I think the "newEnemy" function will be used for all Enemies (anything that can hurt the player).
Enemy type will be set when creating an Enemy and will define how it acts.

Todo:
Add enemies to map.json
Player needs to die when hit with now seeds.
Seeds need to be thrown and bounce when player is hit.
Enemy needs to be hurt when hit with flying seeds.

**Comment by metalx1000** [comment]
@jimfrize I've just hue shifted the player to make the enemy for now.  But if you could make a new sprite, that would be great.  I could do it, but I'm sure you would do a better job.

**Comment by jimfrize** [comment]
@metalx1000 I was just thinking about the "bad guys" :) Been a bit busy recently, hopefully got some time to do a bit more now.

**Comment by jonpatterns** [comment]
Maybe the cats can run home instead of dying?

**Comment by jimfrize** [comment]
@jonpatterns Or they could flip upside down, spring into the air, then just fall off the screen?
Then it's ambigous - did you kill it? Or just scare it off?

**Comment by metalx1000** [comment]
Falling off screen would be easier.  Having them run off won't be hard, except for obstacles that might be in their way.

**Comment by metalx1000** [comment]
We have a few bad guys now.
