### ISSUE TITLE
Playable

### ISSUE THREAD

**Issue by metalx1000** [Awesome-Game-Team/Awesome-Game#34]
The game actually has some things you can do now.
I've done a lot of work the last few days.
@jimfrize I added you background back in, but changed it so that it moved slower then the foreground giving it more of a 3D feel.  Let me know of any proformance issues this might be causing.  I'm hoping now that we are using "CANVAS" things are better.  I also think that @jorgesumle might have had some ideas on improving performance.

We now have 3 different "baddies" to spit seeds at, and they can knock the seeds out of you when hit.  They can be added to the map with the types "jumper", "trooper", and "pacer".

Hope you guys aren't tiring of this project.  I appreciate all your help, but I tend to lose interest in stuff, and you guys working on this keeps me working on this.

Thanks everyone, @jimfrize  @jorgesumle @OneSleepyDev

**Comment by OneSleepyDev** [comment]
In regards to the last part. I'm not tiring :-)
With some school stuff, work stuff, etc. - I've been a bit slow though, and keeping up has been a bit hard, so I apologize.

**Comment by jimfrize** [comment]
@metalx1000 I'm still alive, just busy.

Wow you've done loads of work!
I love how the cats perish, nicely done :)

I've given up on using Firefox or Safari, the game chews on the processor too much. I even made a significantly reduced version of the game, and it still hogs way more than it should do. So I've switched to using Chrome. Things work much smoother on Chrome.

I've got a little time tonight, will see what I can get done. Not sure how much time I will have next week though. The wife has a bug, I've got a load of work to do and I'm preforming at a festival on the weekend.

So much to do, so little time :)

**Comment by jorgesumle** [comment]
I don't have much spare time and I don't know how to use Phaser, but I will try to help from time to time. The game works fine on Firefox for me, but fails on Ubuntu Browser and Chrome.

**Comment by metalx1000** [comment]
@jorgesumle Do you get any errors in the console (F12), or on the page when using Chrome?

**Comment by jonpatterns** [comment]
Game design, at the moment it seems its going to be a fairly typical platformer. I can't get behind a rude boy chick pea stamping on sad cats.

**Comment by jorgesumle** [comment]
I have just tested it with Ubuntu Unity desktop environment, but with Lubuntu desktop environment (LXDE) it just shows a blank screen. I also tested it with Opera and SlimBrowser and it works fine. It shows no error message.

**Comment by jorgesumle** [comment]
I have just tested it on Chrome with Lubuntu desktop environment (LXDE) it just shows a blank screen. I also tested it with Opera and SlimBrowser and it works fine. It shows the following error message:

Phaser v2.4.6 | Pixi.js v2.2.9 | Canvas | WebAudio     http://phaser.io ♥♥♥
phaser.js:72123 XMLHttpRequest cannot load file:///home/jorge/Descargas/Awesome-Game-master/res/map.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.c.Loader.xhrLoad @ phaser.js:72123
phaser.js:71219 Phaser.Loader - tilemap[map]: error loading asset from URL res/map.json
phaser.js:72123 XMLHttpRequest cannot load file:///home/jorge/Descargas/Awesome-Game-master/res/music/TheGame.ogg. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.c.Loader.xhrLoad @ phaser.js:72123
phaser.js:71219 Phaser.Loader - audio[music]: error loading asset from URL res/music/TheGame.ogg
phaser.js:72123 XMLHttpRequest cannot load file:///home/jorge/Descargas/Awesome-Game-master/res/fx/jump.wav. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.c.Loader.xhrLoad @ phaser.js:72123
phaser.js:71219 Phaser.Loader - audio[jump]: error loading asset from URL res/fx/jump.wav
phaser.js:72123 XMLHttpRequest cannot load file:///home/jorge/Descargas/Awesome-Game-master/res/fx/jetpack.wav. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.c.Loader.xhrLoad @ phaser.js:72123
phaser.js:71219 Phaser.Loader - audio[jetpack]: error loading asset from URL res/fx/jetpack.wav
phaser.js:72123 XMLHttpRequest cannot load file:///home/jorge/Descargas/Awesome-Game-master/res/fx/seed.wav. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.c.Loader.xhrLoad @ phaser.js:72123
phaser.js:71219 Phaser.Loader - audio[seed]: error loading asset from URL res/fx/seed.wav
phaser.js:72123 XMLHttpRequest cannot load file:///home/jorge/Descargas/Awesome-Game-master/res/fx/powerup.wav. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.c.Loader.xhrLoad @ phaser.js:72123
phaser.js:71219 Phaser.Loader - audio[powerup]: error loading asset from URL res/fx/powerup.wav
phaser.js:72123 XMLHttpRequest cannot load file:///home/jorge/Descargas/Awesome-Game-master/res/fonts/set1/font.fnt. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.c.Loader.xhrLoad @ phaser.js:72123
phaser.js:71219 Phaser.Loader - bitmapfont[font1]: error loading asset from URL res/fonts/set1/font.fnt
phaser.js:68387 Phaser.Cache.getTilemapData: Key "map" not found in Cache.
phaser.js:94036 Phaser.TilemapParser.parse - No map data found for key map
phaser.js:90596 Uncaught TypeError: Cannot read property 'width' of undefined

![captura de pantalla de 2016-06-03 03 41 42](https://cloud.githubusercontent.com/assets/14212780/15766315/55d6ce98-293d-11e6-8ef2-0ca9dc5b850f.png)

**Comment by metalx1000** [comment]
@jorgesumle Looks like you are trying to run it by opening the file directly.  I'm surprised this worked in any browser.  It should, that would be a security risk.  Either spin up your own web server to access it, or try the link on my site:
http://filmsbykris.com/scripts/Awesome-Game/

**Comment by metalx1000** [comment]
@jonpatterns it's pretty basic now, but that is why we are working on it.  If you want it to be more, then make it something more.  What is it you want to see the game do?

Also, are you serious about the "rude boy chick pea stamping on sad cats" comment, or was that meant  to be a joke?

People, these aren't real cats.  Nothing is dying for real.  It's just a game.
