### ISSUE TITLE
Scrolling Background Images

### ISSUE THREAD

**Issue by jimfrize** [Awesome-Game-Team/Awesome-Game#5]
I'd really like to try and implement a scrolling background that creates a sort of pseudo-3D parallaxing pan effect. Perhaps some line drawn cityscapes would look nice?

**Comment by OneSleepyDev** [comment]
Is that the same effect used for Super Mario World? (2 layer background, clouds, leaves falling, mountains, etc.)
Forgive me for my ignorance. :p

**Comment by metalx1000** [comment]
Sleepy (can I call you that?),
I think be means something like that.
Could be a still image (repeating pattern probably), that moves a bit slower then the front layer.
And we can also have an animated as well.

I've only played with tilemaps a little bit.
I've created the current level quickly with Tiled (http://www.mapeditor.org/).
It's in the repositories for Debian, so I'm assuming other Linux distros as well.
Or you can get it from the website if you are feeling adventurous.  :D

**Comment by OneSleepyDev** [comment]
Fine with me, it's accurate. I just abbrev to osd when I'm feeling lazy.

That sounds good to me! Although, I have almost zero experience with using tilemaps.
(The most I've done is stretch an image)

**Comment by jimfrize** [comment]
When I get the time I can put together a seamless background image.

**Comment by OneSleepyDev** [comment]
@jimfrize You've already been doing so much, hope this isn't too much to ask.
When you have time would you mind creating a farm looking background? I thought it might go well with the chickpea character.

I can see it now.. :corn:  "Episode 1: Escape the farm!" :leaves:

**Comment by jimfrize** [comment]
@OneSleepyDev Once we have worked out the right way to do the backgrounds, I'll make a whole bunch of different scenes :)

**Comment by metalx1000** [comment]
Look at my latest push and tell me what you think of the background movement.

**Comment by jimfrize** [comment]
@metalx1000 Superb work, looks great!
