### ISSUE TITLE
Music file size and asset licenses

### ISSUE THREAD

**Issue by OneSleepyDev** [Awesome-Game-Team/Awesome-Game#6]
@jimfrize 
Thanks for the updates! :D
I like what you did, but a few problems came up.

TheGame.wav is 19MB :/ Could we try to make that file smaller?
And so that we're certain the files(player.png, jump.wav, thegame.wave) can be used, could you post the licenses?

**Comment by metalx1000** [comment]
Wow, thanks for for catching that.  Yeah, that's huge.
I'll make the music file smaller.  I'm pretty sure @jimfrize made the player.png.

@jimfrize I should have asked you.  Did you make the music and jump sound?  If not, were did you get them and do we have the right to be using them?  If this jump sound doesn't work, I have some jump sounds I've created for other projects with a synthesizer.  If we can't use the music, there is plenty of out there we can use.

**Comment by metalx1000** [comment]
@OneSleepyDev I've reduced the size of the Wave files and made mp3 and ogg copies for compatibility.  Still waiting on @jimfrize  about the licensing.

**Comment by jimfrize** [comment]
I made the music and jump sound, I am happy to share them as part of the project under the license you are currently using for the project. Also the music and FX are just demos really, I am more than happy to change them to your liking. I work in music, so the sound design stuff is kind of my forte. Apologies for the huge file size!

**Comment by jimfrize** [comment]
Yeah, the player.png is my design too. I drew it on paper and scanned it in. I thought the game would suit a more hand drawn style. I plan to do the same for the blocks and bricks, if that is of any interest?

**Comment by jimfrize** [comment]
...and yeah, the slow moving backgrounds inSuper Mario World is exactly what I was thinking. It would be a really nice feature.

**Comment by jimfrize** [comment]
With the music I took some cues from Kris' original. The bass line has the same melody and it uses 8 bit style synthesizers. But like I said, I can do what ever you want.

**Comment by OneSleepyDev** [comment]
@metalx1000 When the page took a minute to load I realized something was strange. lol

@jimfrize They sound great! And thank you for being so prompt!

**Comment by jimfrize** [comment]
@OneSleepyDev No problem, I'm excited to be part of the project, as you can probably see from my Github profile, I don't normally do this kind of thing. I've been watching Kris for a while on Youtube and he's been a constant source of inspiration :)

**Comment by OneSleepyDev** [comment]
@jimfrize Ditto! :laughing:

**Comment by jimfrize** [comment]
The music size and format is interesting. To get the size down @metalx1000 has reduced the WAV to a sampling rate of 22.05K and a bit depth of 8, it's also mono. And to be honest, the sound quality of the WAV is pretty bad. The Mp3 on the other hand is a smaller file size, 44.1K and stereo - it sounds significantly better. I've also found that the OGG format is not so well supported and, in my experience, when using that format with a variety of music players and audio software I've had a lot of problems (including unintentionally blasting people with high volume white noise whilst DJing - oops!). What's everyones thoughts on this matter? Is it worth providing WAV and OGG?

**Comment by OneSleepyDev** [comment]
@jimfrize I tried to lower the size of a wav on my project and it ended up sounding awful. x_x so I used mp3 - But OGG is the go to format for Free Software users, so including it along with mp3 would be a good idea IMHO. Some people don't and can't use mp3's due to restrictions. (IIRC, MP3 has a fuzzy legal status)

**Comment by metalx1000** [comment]
Yes, we should definitely support OGG, and maybe WAV.  Mp3 is a horrible format, and is not suitable for Free browsers such as Firefox.  But, some browsers refuse to support OGG, IE for example.  

Now, WAV files are larger and there is quality loss so get the file size down, but they load a lot faster.  Most browsers don't state that they support WAV, but even though they don't say it, most do support it.  MP3's and OGG files need to be decompressed.  On some mobile devices (my phone) this could take up to 5 seconds for a short song.  It's faster to download a larger WAV file and play it than to decode an MP3.  If we choose to get ride of WAV files, we have two options.  Have the game start, and the must starts a few seconds later once it had loaded, or have the game wait for the MP3/OGG files to load and decode before the game starts.  

This is not a problem.  I've done it before with games.  It's different than the "Preload" function, which just makes sure the file is downloaded.  This will be an extra function that just holds loading the game until the music is read to play.

**Comment by OneSleepyDev** [comment]
@metalx1000 I see your point with wav. And I wouldn't mind a loading screen with a progress bar if I was playing the game. I wait through those things all the time anyway.

**Comment by jimfrize** [comment]
So for free and open ware, OGG is well supported - good to know! In my case, I can't play the OGG file using Safari. But I can use MP3 and WAV. Even though MP3 is an evil proprietary format, it's preferable to the low quality WAV. If we keep WAV, is there someway to make MP3 and OGG Vorbis the default, then have the WAV file as a last resort?

**Comment by metalx1000** [comment]
Well, the whole point of using the WAV is for quicker loading.  So if we are going to use it, it should be the default, other wise we shouldn't be using it.

**Comment by jimfrize** [comment]
@metalx1000 Ahh ok, I see what you mean now. I'm happy to go with the general consensus, but personally speaking, if we had to use WAVs @ 8bit and 22.05, I'd rather not use WAVs at all.

**Comment by metalx1000** [comment]
@jimfrize I agree.  We could do better with our code and create a loading screen.
This isn't high priority for me.  For now we can remove the WAV file and just have delayed music on slower devices.  It's not like we have a huge audience at this point and it doesn't effect Game play.

**Comment by metalx1000** [comment]
All Wav files have been removed (for music) and OGG/MP3 are being used.  Closing this.
