### ISSUE TITLE
Touch screen controls

### ISSUE THREAD

**Issue by metalx1000** [Awesome-Game-Team/Awesome-Game#9]
Some basic onscreen controls for touch screen devices.
Basic concept is like the jump button I put in this game I created a while back:
http://filmsbykris.com/scripts/Game-Basics/Phaser2D/tutorials/tmnt/09_tutorial.html

Or if someone wants to be more creative I'd love to see what people come up with

**Comment by jimfrize** [comment]
This would be a great addition, let me know if you need some custom icons for the controls.

**Comment by metalx1000** [comment]
Custom icons would be great.  I could just make left and right arrow, and circle buttons for other controls, but maybe you can make something better.  right now we need,
Left, Right, Jump, Jetpack buttons

Here are some ideas from the Phaser site.  
http://phaser.io/examples/v2/category/virtualjoystick

**Comment by jimfrize** [comment]
@metalx1000 Please see my latest pull request, I have made some simple icons for this feature. They are in the res folder, but they are not implemented in any way. I have tried them out on screen though, and they look good.

**Comment by jimfrize** [comment]
Here's what they look like:

<img width="800" alt="control_mock" src="https://cloud.githubusercontent.com/assets/12966015/15300606/661aad28-1ba1-11e6-8efa-e182f423e891.png">

**Comment by jimfrize** [comment]
If people like them, maybe I could do another mute icon in the same style

**Comment by OneSleepyDev** [comment]
@jimfrize Those look pretty awesome! Could the opacity be tweaked a little? :-)

**Comment by jimfrize** [comment]
@OneSleepyDev Sure, no problem. I did try them with a little transparency, but it made them harder to see over certain tiles. We can give the transparent ones a spin once we have the controls up and running :) I'm loving the square clouds at the moment, quite pleased with them. The temple thing was supposed to have a Tux penguin above the door, not sure where that's gone?

**Comment by metalx1000** [comment]
Looks great!  I like @OneSleepyDev idea of transparency level tweak on the controls.  This should be able to be done in code.

**Comment by metalx1000** [comment]
I've added the basic controls.  I still need to add a Jetpack button and any other buttons we may need as functions are added.
